version: '3.8'

x-common-variables: &common-variables
  DEBUG: "False"
  SECRET_KEY: ${SECRET_KEY:-change_me_in_production}
  DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1] ${PUBLIC_IP} ${DOMAIN_NAME} 47.94.195.221"
  DATABASE_ENGINE: "django.db.backends.mysql"
  DATABASE_NAME: ${DB_NAME:-test_platform}
  DATABASE_USER: ${DB_USER:-root1}
  DATABASE_PASSWORD: ${DB_PASSWORD:-Lhx7758521003!}
  DATABASE_HOST: ${DB_HOST:-rm-bp1187tb295ka68e9lo.mysql.rds.aliyuncs.com}
  DATABASE_PORT: ${DB_PORT:-3306}
  REDIS_HOST: ${REDIS_HOST:-47.94.195.221}
  REDIS_PORT: ${REDIS_PORT:-6379}
  CORS_ALLOWED_ORIGINS: "http://47.94.195.221:8010"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: auto_platform_web
    restart: always
    dns:
      - 223.5.5.5  # 阿里云公共DNS
      - 223.6.6.6  # 阿里云公共DNS备用
    extra_hosts:
      - "rm-bp1187tb295ka68e9lo.mysql.rds.aliyuncs.com:${DB_IP:-47.94.195.221}"  # 如果需要，可以设置主机名到特定IP的映射
    environment:
      <<: *common-variables
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/login/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto_platform_celery
    restart: always
    dns:
      - 223.5.5.5  # 阿里云公共DNS
      - 223.6.6.6  # 阿里云公共DNS备用
    extra_hosts:
      - "rm-bp1187tb295ka68e9lo.mysql.rds.aliyuncs.com:${DB_IP:-47.94.195.221}"  # 如果需要，可以设置主机名到特定IP的映射
    depends_on:
      web:
        condition: service_started
    environment:
      <<: *common-variables
    volumes:
      - ./:/app
    command: "/app/celery-entrypoint.sh"

volumes:
  static_volume:
  media_volume: