version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: auto_platform_db
    restart: always
    environment:
      - MYSQL_DATABASE=auto_platform
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: auto_platform_web
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=False
      - SECRET_KEY=change_me_in_production
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_ENGINE=django.db.backends.mysql
      - DATABASE_NAME=auto_platform
      - DATABASE_USER=dbuser
      - DATABASE_PASSWORD=dbpassword
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               gunicorn --bind 0.0.0.0:8000 auto_platform.wsgi:application"

volumes:
  mysql_data:
  static_volume:
  media_volume: 