# Generated by Django 4.2.20 on 2025-04-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0002_alter_testresult_test_result_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='last_executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='last_execution_result',
            field=models.CharField(default='not_run', max_length=20, verbose_name='最后执行结果'),
        ),
    ]
