# Generated by Django 4.2.17 on 2024-12-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0003_project_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='状态是否活跃'),
        ),
    ]
