# Generated by Django 4.2.20 on 2025-04-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0003_alter_testcase_last_executed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='case_extractors',
            field=models.TextField(blank=True, db_comment='测试结果提取器配置', null=True, verbose_name='提取器'),
        ),
    ]
