# Generated by Django 4.2.20 on 2025-04-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0004_testcase_case_extractors'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='case_tests',
            field=models.TextField(blank=True, db_comment='测试断言配置', null=True, verbose_name='测试断言'),
        ),
    ]
