# Generated by Django 4.2.17 on 2024-12-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0004_project_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.IntegerField(default=0, verbose_name='状态是否活跃'),
        ),
    ]
