# Generated by Django 4.2.17 on 2024-12-12 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_platform', '0005_alter_project_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('test_case_id', models.AutoField(db_comment='测试用例的唯一标识', primary_key=True, serialize=False, verbose_name='用例ID')),
                ('case_name', models.CharField(db_comment='测试用例的名称', max_length=255, verbose_name='用例名称')),
                ('case_description', models.TextField(db_comment='对测试用例的详细描述', verbose_name='用例描述')),
                ('case_path', models.CharField(db_comment='测试用例的文件路径', max_length=255, verbose_name='用例路径')),
                ('case_request_method', models.CharField(db_comment='HTTP请求方法', max_length=255, verbose_name='请求方法')),
                ('case_priority', models.IntegerField(choices=[(0, '低'), (1, '中'), (2, '高')], db_comment='测试用例的优先级', default=0, verbose_name='用例优先级')),
                ('case_status', models.IntegerField(choices=[(0, '未执行'), (1, '已执行')], db_comment='测试用例的执行状态', default=0, verbose_name='用例执行状态')),
                ('case_params', models.TextField(db_comment='HTTP请求参数', verbose_name='请求参数')),
                ('case_precondition', models.TextField(db_comment='执行测试用例前的条件', verbose_name='前置条件')),
                ('case_request_headers', models.TextField(db_comment='HTTP请求头信息', verbose_name='请求头')),
                ('case_requests_body', models.TextField(db_comment='HTTP请求体内容', verbose_name='请求体')),
                ('case_expect_result', models.TextField(db_comment='测试用例的预期结果', verbose_name='期望结果')),
                ('case_assert_type', models.CharField(blank=True, db_comment='断言的类型', max_length=50, null=True, verbose_name='断言类型')),
                ('case_assert_contents', models.TextField(db_comment='断言的具体内容', verbose_name='断言内容')),
                ('creat_time', models.DateTimeField(auto_now_add=True, db_comment='测试用例的创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_comment='测试用例的最后更新时间', verbose_name='更新时间')),
                ('last_executed_at', models.DateTimeField(blank=True, db_comment='最后一次执行测试用例的时间', null=True, verbose_name='最近执行时间')),
                ('last_execution_result', models.CharField(choices=[('passed', '通过'), ('failed', '失败'), ('blocked', '阻塞'), ('not_run', '未执行')], db_comment='最近一次执行的结果', default='not_run', max_length=20, verbose_name='最近执行结果')),
                ('creator', models.ForeignKey(db_comment='创建该测试用例的用户', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(db_comment='关联的项目', on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='test_platform.project', verbose_name='项目')),
            ],
        ),
    ]
