# Generated by Django 4.2.20 on 2025-04-25 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_platform', '0005_testcase_case_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('suite_id', models.AutoField(primary_key=True, serialize=False, verbose_name='套件ID')),
                ('name', models.CharField(max_length=255, verbose_name='套件名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='套件描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
                ('last_execution_status', models.CharField(default='not_run', max_length=20, verbose_name='最后执行状态')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_suites', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_suites', to='test_platform.testenvironment', verbose_name='执行环境')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='test_platform.project', verbose_name='所属项目')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuiteCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_case_id', models.IntegerField(verbose_name='原始用例ID')),
                ('case_data', models.TextField(help_text='JSON格式的测试用例数据', verbose_name='用例数据')),
                ('order', models.IntegerField(default=0, verbose_name='执行顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_cases', to='test_platform.testsuite', verbose_name='测试套件')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('suite', 'original_case_id')},
            },
        ),
    ]
