# Generated by Django 4.2.20 on 2025-04-25 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_platform', '0006_testsuite_testsuitecase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuiteResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False, verbose_name='结果ID')),
                ('execution_time', models.DateTimeField(verbose_name='执行时间')),
                ('status', models.CharField(choices=[('pass', '通过'), ('fail', '失败'), ('error', '错误'), ('skip', '跳过'), ('partial', '部分通过')], max_length=20, verbose_name='执行状态')),
                ('duration', models.FloatField(default=0, help_text='单位：秒', verbose_name='执行时长')),
                ('total_cases', models.IntegerField(default=0, verbose_name='用例总数')),
                ('passed_cases', models.IntegerField(default=0, verbose_name='通过用例数')),
                ('failed_cases', models.IntegerField(default=0, verbose_name='失败用例数')),
                ('error_cases', models.IntegerField(default=0, verbose_name='错误用例数')),
                ('skipped_cases', models.IntegerField(default=0, verbose_name='跳过用例数')),
                ('pass_rate', models.FloatField(default=0, verbose_name='通过率')),
                ('result_data', models.TextField(help_text='JSON格式的详细结果数据', verbose_name='结果数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite_results', to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suite_results', to='test_platform.testenvironment', verbose_name='执行环境')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_results', to='test_platform.testsuite', verbose_name='测试套件')),
            ],
        ),
    ]
