# Generated by Django 4.2.20 on 2025-04-30 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0008_testcase_last_assertion_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='environment_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_suites', to='test_platform.testenvironmentcover', verbose_name='执行环境套'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_suites_env', to='test_platform.testenvironment', verbose_name='执行环境'),
        ),
    ]
