# Generated by Django 4.2.20 on 2025-04-30 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_platform', '0009_testsuite_environment_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestExecutionLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='日志ID')),
                ('execution_time', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('status', models.CharField(choices=[('pass', '通过'), ('fail', '失败'), ('error', '错误'), ('skip', '跳过')], max_length=20, verbose_name='执行状态')),
                ('duration', models.FloatField(default=0, verbose_name='执行时长(秒)')),
                ('request_url', models.TextField(blank=True, null=True, verbose_name='请求URL')),
                ('request_method', models.CharField(blank=True, max_length=20, null=True, verbose_name='请求方法')),
                ('request_headers', models.TextField(blank=True, null=True, verbose_name='请求头')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='请求体')),
                ('response_status_code', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('response_headers', models.TextField(blank=True, null=True, verbose_name='响应头')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='响应体')),
                ('log_detail', models.TextField(blank=True, null=True, verbose_name='详细日志')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('extracted_variables', models.TextField(blank=True, null=True, verbose_name='提取的变量')),
                ('assertion_results', models.TextField(blank=True, null=True, verbose_name='断言结果')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='test_platform.testcase', verbose_name='测试用例')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='test_platform.testenvironment', verbose_name='执行环境')),
                ('environment_cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='test_platform.testenvironmentcover', verbose_name='环境套')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='test_platform.testsuite', verbose_name='测试套件')),
            ],
            options={
                'verbose_name': '执行日志',
                'verbose_name_plural': '执行日志',
                'ordering': ['-execution_time'],
            },
        ),
    ]
