# Generated by Django 4.2.20 on 2025-04-30 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_platform', '0012_remove_testexecutionlog_test_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False, verbose_name='计划ID')),
                ('name', models.CharField(max_length=255, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='计划描述')),
                ('schedule_type', models.CharField(choices=[('once', '一次性'), ('daily', '每天'), ('weekly', '每周'), ('cron', '定时任务')], default='once', max_length=20, verbose_name='调度类型')),
                ('execute_time', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('cron_expression', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cron表达式')),
                ('retry_times', models.IntegerField(default=0, verbose_name='重试次数')),
                ('notify_types', models.CharField(blank=True, max_length=255, null=True, verbose_name='通知类型')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='test_platform.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='TestPlanResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False, verbose_name='结果ID')),
                ('execution_time', models.DateTimeField(verbose_name='执行时间')),
                ('status', models.CharField(choices=[('pass', '通过'), ('fail', '失败'), ('error', '错误'), ('partial', '部分通过'), ('cancelled', '已取消')], max_length=20, verbose_name='执行状态')),
                ('duration', models.FloatField(default=0, help_text='单位：秒', verbose_name='执行时长')),
                ('total_suites', models.IntegerField(default=0, verbose_name='套件总数')),
                ('passed_suites', models.IntegerField(default=0, verbose_name='通过套件数')),
                ('failed_suites', models.IntegerField(default=0, verbose_name='失败套件数')),
                ('error_suites', models.IntegerField(default=0, verbose_name='错误套件数')),
                ('total_cases', models.IntegerField(default=0, verbose_name='用例总数')),
                ('passed_cases', models.IntegerField(default=0, verbose_name='通过用例数')),
                ('failed_cases', models.IntegerField(default=0, verbose_name='失败用例数')),
                ('error_cases', models.IntegerField(default=0, verbose_name='错误用例数')),
                ('skipped_cases', models.IntegerField(default=0, verbose_name='跳过用例数')),
                ('pass_rate', models.FloatField(default=0, verbose_name='通过率')),
                ('result_data', models.TextField(help_text='JSON格式的详细结果数据', verbose_name='结果数据')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_results', to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_results', to='test_platform.testplan', verbose_name='测试计划')),
            ],
            options={
                'verbose_name': '测试计划结果',
                'verbose_name_plural': '测试计划结果',
                'ordering': ['-execution_time'],
            },
        ),
        migrations.CreateModel(
            name='TestPlanSuite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0, verbose_name='执行顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_suites', to='test_platform.testenvironment', verbose_name='执行环境')),
                ('environment_cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_suites', to='test_platform.testenvironmentcover', verbose_name='环境套')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_suites', to='test_platform.testplan', verbose_name='测试计划')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_suites', to='test_platform.testsuite', verbose_name='测试套件')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('plan', 'suite')},
            },
        ),
    ]
