# Generated by Django 4.2.20 on 2025-05-06 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_platform', '0014_ragknowledgebase_ragquery_ragfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('api_key_id', models.AutoField(primary_key=True, serialize=False, verbose_name='密钥ID')),
                ('key_name', models.CharField(max_length=100, verbose_name='密钥名称')),
                ('api_key', models.CharField(max_length=500, verbose_name='API密钥')),
                ('api_base', models.CharField(default='https://api.coze.cn', max_length=200, verbose_name='API基础URL')),
                ('service_type', models.CharField(choices=[('coze', 'Coze'), ('openai', 'OpenAI'), ('zhipu', '智谱AI'), ('deepseek', 'DeepSeek'), ('other', '其他')], default='coze', max_length=20, verbose_name='服务类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('rate_limit', models.IntegerField(default=0, help_text='0表示无限制', verbose_name='速率限制(每分钟)')),
                ('token_limit', models.IntegerField(default=0, help_text='0表示无限制', verbose_name='令牌限制(每月)')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='test_platform.project', verbose_name='关联项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': 'API密钥',
                'verbose_name_plural': 'API密钥',
                'ordering': ['-create_time'],
                'unique_together': {('user', 'key_name')},
            },
        ),
    ]
