# Generated by Django 4.2.20 on 2025-05-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0015_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='config',
            field=models.TextField(blank=True, help_text='JSON格式的额外配置参数', null=True, verbose_name='配置信息'),
        ),
    ]
