# Generated by Django 4.2.20 on 2025-05-07 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_platform', '0016_apikey_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False, verbose_name='分析ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('deepseek_response', models.TextField(blank=True, null=True, verbose_name='DeepSeek响应')),
                ('sheets_data', models.TextField(blank=True, null=True, verbose_name='解析的表格数据')),
                ('test_cases_data', models.TextField(blank=True, null=True, verbose_name='测试用例数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_results', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='test_platform.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'AI分析结果',
                'verbose_name_plural': 'AI分析结果',
                'ordering': ['-create_time'],
            },
        ),
    ]
