# Generated by Django 4.2.20 on 2025-05-09 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test_platform', '0017_analysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMindMap',
            fields=[
                ('mindmap_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='脑图名称')),
                ('data', models.TextField(verbose_name='脑图数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindmaps', to='test_platform.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试脑图',
                'verbose_name_plural': '测试脑图',
                'db_table': 'test_platform_testmindmap',
                'ordering': ['-update_time'],
            },
        ),
    ]
